services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ml-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./temp_data:/app/temp_data
      - ./results:/app/results
    environment:
      - PYTHONUNBUFFERED=1
